### ISSUE TITLE
There is no current event loop in thread 'Thread-1'

### ISSUE THREAD

**Issue by happyfmy** [Mumuzi7179/SQLBlind_Flow_Crack#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\software\python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\software\python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXX\Desktop\SQLBlind_Flow_Crack-main\gui.pyw", line 38, in run_crack_thread
    output = mains(selected_file_path)
  File "C:\Users\XXX\Desktop\SQLBlind_Flow_Crack-main\crack.py", line 138, in mains
    jt = judgtype(pcap_file)
  File "C:\Users\XXX\Desktop\SQLBlind_Flow_Crack-main\extract.py", line 7, in judgtype
    packets = pyshark.FileCapture(pcap_file, display_filter='http')
  File "D:\software\python39\lib\site-packages\pyshark\capture\file_capture.py", line 38, in __init__
    super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
  File "D:\software\python39\lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
  File "D:\software\python39\lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "D:\software\python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.

**Comment by Mumuzi7179** [comment]
我将gui.pyw代码修改了一下，师傅再下载试试呢？

**Comment by happyfmy** [comment]
> 我将gui.pyw代码修改了一下，师傅再下载试试呢？

还是一样的报错呢

python3 .\gui.pyw
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\software\python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\software\python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\Desktop\SQLBlind_Flow_Crack-main\gui.pyw", line 47, in run_crack_thread
    output = mains(selected_file_path)
  File "C:\Users\xxx\Desktop\SQLBlind_Flow_Crack-main\crack.py", line 138, in mains
    jt = judgtype(pcap_file)
  File "C:\Users\xxx\Desktop\SQLBlind_Flow_Crack-main\extract.py", line 7, in judgtype
    packets = pyshark.FileCapture(pcap_file, display_filter='http')
  File "D:\software\python39\lib\site-packages\pyshark\capture\file_capture.py", line 38, in __init__
    super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
  File "D:\software\python39\lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
  File "D:\software\python39\lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "D:\software\python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.

**Comment by Kkkkkkkotori** [comment]
我也是同样的报错 (

**Comment by Mumuzi7179** [comment]
经研究，发现我之前本地用的pyshark版本是21年2月的0.4.3版本，而最新已经更新到了23年4月的0.6版本，在0.5版本的时候pyshark进行过一次大改，具体没有去看，暂时猜测跟此次报错有关，类似于https://github.com/KimiNewt/pyshark/issues/611里的错误，在其中提到添加
 loop = asyncio.new_event_loop() # Create a new event loop in the thread
 asyncio.set_event_loop(loop) # Set the new event loop as the current loop

(然后也在pyshark的Contributors里看到了miao师傅的身影，不愧是miao师傅)
师傅们可以下载最新的版本进行测试，并且已更新requirements.txt，如果python版本小于3.4请单独安装asyncio库
(其实思考是让你们降级还是我升级，虽然升级后感觉麻烦一点不过"与时俱进"还是不错的）

**Comment by Kkkkkkkotori** [comment]
可以打开了，感谢套神的飞速更新
